// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOrderOfService(arg1:string):Promise<main.OrderOfService>;

export function GetOrderOfServices():Promise<Array<main.OrderOfService>>;

export function GetSong(arg1:string):Promise<main.Song>;

export function GetSongs():Promise<Array<main.Song>>;

export function LoadSong():Promise<main.SongSlide>;
