// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataStore() {
  return window['go']['main']['App']['GetDataStore']();
}

export function GetSong(arg1) {
  return window['go']['main']['App']['GetSong'](arg1);
}

export function LoadSong() {
  return window['go']['main']['App']['LoadSong']();
}
