// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDataStore():Promise<main.DataStore>;

export function GetSong(arg1:string):Promise<main.Song>;

export function LoadSong():Promise<main.SongSlide>;
