// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData(arg1, arg2) {
  return window['go']['main']['App']['GetData'](arg1, arg2);
}

export function GetOrderOfService(arg1) {
  return window['go']['main']['App']['GetOrderOfService'](arg1);
}

export function GetOrderOfServices() {
  return window['go']['main']['App']['GetOrderOfServices']();
}

export function GetSong(arg1) {
  return window['go']['main']['App']['GetSong'](arg1);
}

export function GetSongs() {
  return window['go']['main']['App']['GetSongs']();
}

export function LoadSong() {
  return window['go']['main']['App']['LoadSong']();
}
