// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetData(arg1) {
  return window['go']['main']['DisplayServer']['SetData'](arg1);
}
